# Site settings
title: borntyping
email: sam@borntyping.co.uk
username: borntyping
description: ""
baseurl: ""
url: "http://borntyping.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
