# Site settings
title: borntyping
email: sam@borntyping.co.uk

# Theme settings
author:
  name: "Sam Clements"
  url: "https://borntyping.co.uk"
tagline: "Sam Clements"

# Build settings
permalink: pretty

# Frontmatter defaults
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
