# Site settings
title: borntyping
email: sam@borntyping.co.uk

# Theme settings
author:
  name: "Sam Clements"
  url: "http://borntyping.io"
tagline: "Sam Clements"

# Build settings
permalink: pretty
paginate: 5

# Frontmatter defaults
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
