# Site settings
title: borntyping
email: sam@borntyping.co.uk
url: "http://borntyping.io"

# Theme settings
author:
  name: "Sam Clements"
  url: "http://borntyping.io"
tagline: "Sam Clements"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5

# Frontmatter defaults
defaults:
  -
    scope:
      path: ''
      type: 'post'
    values:
      layout: 'post'
